#!/usr/bin/env bash

source "$(dirname "$0")/../sourcedialog"

sd_load_canvas  name=canvas1  x=3  y=3 width=73 height=18 caption="EXAMPLE 2"

sd_load_frame   name=frame1   x=4  y=5 width=17 height=12
sd_load_textbox name=textbox1 x=5  y=6 width=15 height=10 \
                text="This text is automatically wrapped"

sd_load_frame   name=frame2   x=22 y=5 width=17 height=12
sd_load_textbox name=textbox2 x=23 y=6 width=15 height=10 \
                text="This\ntext\nis\nforced\nto\nwrap\nevery\nword"

sd_load_frame   name=frame3   x=40 y=5 width=17 height=12
sd_load_textbox name=textbox3 x=41 y=6 width=15 height=10 \
                text="Be careful in veryverylongwords because words greather than width will be truncated"

sd_load_frame   name=frame4   x=58 y=5 width=17 height=12
sd_load_textbox name=textbox4 x=59 y=6 width=15 height=10 \
                text="You have to define a rectangle large enough to fill every word you think to write, because if your rectangle is too small, your text will be truncated"

sd_load_pushbutton name=button1 x=35 y=19 caption="  OK  "
sd_button1_push () { return 0; }

sd_start; retval=$?
clear
case $retval in
  27)  echo "Esc pressed." ;;
  0)   echo "OK pressed." ;;
esac
