#!/usr/bin/env bash
source "$(dirname "$0")/../sourcedialog"

array=( "Linux   The Great Unix Clone for 386/486" \
        "NetBSD  Another free Unix Clone for 386/486" \
        "OS/2    IBM OS/2" \
        "WIN NT  Microsoft Windows NT" \
        "PCDOS   IBM PC DOS" \
        "MSDOS   Microsoft DOS" )
comment=


sd_load_canvas     name=cvmain   x=13 y=4  width=51 height=16
sd_load_textbox    name=tbtext   x=15 y=5  text="Choose the OS you like"
sd_load_frame      name=cvos     x=15 y=6  width=47 height=6 
sd_load_menubox    name=mbos     x=17 y=7  width=43 height=4 arrayname=array
sd_load_textbox    name=tbwhy    x=15 y=13 text="Your comment here..."
sd_load_frame      name=frcomm   x=15 y=14 width=47 height=3
sd_load_inputbox   name=ibcomm   x=16 y=15 width=45 varname=comment
sd_load_pushbutton name=pbok     x=27 y=18 caption="  OK  "
sd_load_pushbutton name=pbcancel x=42 y=18 caption="Cancel"

sd_pbok_push ()     { index=$sd_mbos_ilight; return 0; }
sd_pbcancel_push () { return 1; }


sd_start; retval=$?
clear
case $retval in
  27) echo "ESC pressed." ;;
  1)  echo "Cancel pressed." ;;
  0)  
    echo "${array[$index]} chosen."
    echo
    echo "comment: $comment"
    ;;
esac
